import assert from "node:assert/strict";
import test from "node:test";
import { ACTION_DELAY_BASE, SpdTimeline, computeActionDelay } from "../dist/battle/timeline.js";
test("action delay follows the approved SPD formula",()=>{assert.equal(computeActionDelay(100),100);assert.equal(computeActionDelay(80),125);assert.equal(computeActionDelay(125),80);assert.equal(computeActionDelay(100,0.85),85);assert.equal(ACTION_DELAY_BASE,10_000);});
test("faster actors act earlier and repeated scheduling remains deterministic",()=>{const timeline=new SpdTimeline();timeline.registerActor({id:"zhao-yun",spd:120});timeline.registerActor({id:"guan-yu",spd:100});timeline.registerActor({id:"zhang-fei",spd:80});const order=[];for(let count=0;count<7;count+=1){const event=timeline.takeNext();assert.ok(event);order.push(event.actorId);timeline.scheduleAfterAction(event.actorId);}assert.deepEqual(order,["zhao-yun","guan-yu","zhang-fei","zhao-yun","guan-yu","zhang-fei","zhao-yun"]);});
test("equal-speed ties resolve by deterministic registration/schedule order",()=>{const timeline=new SpdTimeline();timeline.registerActor({id:"a",spd:100});timeline.registerActor({id:"b",spd:100});assert.equal(timeline.takeNext()?.actorId,"a");assert.equal(timeline.takeNext()?.actorId,"b");});
test("timeline advance and delay shift the next normal action",()=>{const timeline=new SpdTimeline();timeline.registerActor({id:"a",spd:100});timeline.registerActor({id:"b",spd:100});timeline.shiftNextNormalAction("b",-30);assert.equal(timeline.takeNext()?.actorId,"b");timeline.shiftNextNormalAction("a",40);const a=timeline.takeNext();assert.ok(a);assert.equal(a.actorId,"a");assert.equal(a.readyAt,140);});
test("interrupt and extra actions take deterministic priority at the same time",()=>{const timeline=new SpdTimeline();timeline.registerActor({id:"a",spd:100});timeline.registerActor({id:"b",spd:100});const first=timeline.takeNext();assert.ok(first);assert.equal(first.actorId,"a");assert.equal(timeline.time,100);timeline.scheduleExtraAction("a",0);timeline.scheduleInterrupt("b");assert.deepEqual([timeline.takeNext(),timeline.takeNext()].map((event)=>[event?.actorId,event?.kind]),[["b","interrupt"],["a","extra"]]);});
test("removing a KO actor clears its scheduled actions",()=>{const timeline=new SpdTimeline();timeline.registerActor({id:"a",spd:120});timeline.registerActor({id:"b",spd:100});timeline.removeActor("a");assert.equal(timeline.hasActor("a"),false);assert.deepEqual(timeline.peek().map((event)=>event.actorId),["b"]);});
